[pve]
pve-01.prod.dc1.kawasaki-n3t.f5.si
pve-02.prod.dc1.kawasaki-n3t.f5.si
pve-03.prod.dc1.kawasaki-n3t.f5.si

[pbs]
pbs-01.prod.dc1.kawasaki-n3t.f5.si

[pve:vars]
ansible_user=root

[pbs:vars]
ansible_user=root

[cluster:children]
pve
pbs
