[pve]
pve-01.prod.dc1.kawasaki-n3t.f5.si
pve-02.prod.dc1.kawasaki-n3t.f5.si
pve-03.prod.dc1.kawasaki-n3t.f5.si

[pbs]
pbs-01.prod.dc1.kawasaki-n3t.f5.si

[dpl]
dpl-01.prod.dc1.kawasaki-n3t.f5.si
dpl-02.prod.dc1.kawasaki-n3t.f5.si

[pve:vars]
ansible_user=root

[pbs:vars]
ansible_user=root

[dpl:vars]
ansible_user=kawasaki
ansible_become=true
ansible_become_method=sudo
ansible_ssh_extra_args='-tt'

[cluster:children]
pve
pbs
dpl
